# render.yaml
services:
  - type: web
    name: cryptopred  
    env: python
    buildCommand: "pip install -r requirements.txt"  # Install dependencies
    startCommand: "flask run --host=0.0.0.0 --port=10000"  # Start Flask server
    envVars:
      - key: FLASK_ENV
        value: production  # Use 'development' if you want debug mode
      - key: NEWS_API_KEY
        sync: false  # This way it won't expose your secret API key
    plan: free  # Render’s free plan for initial testing

    # Optional health check path
    healthCheckPath: "/"

    # Port configuration
    autoDeploy: true
    branch: master  # Specify the branch to deploy
